apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kerstholt-top-tls
spec:
  secretName: kerstholt-top-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kerstholt.top
  dnsNames:
    - kerstholt.top
    - www.kerstholt.top
