apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  # When applying this config, Kubernetes is going to find a Persistent Volume that meets the below requirements.
  accessModes:
    # ReadWriteOnce means only one Pod can write to the storage (not suitable for database with multiple replicas!)
    - ReadWriteOnce
  resources:
    requests:
      # Mi = Mebibyte (~Megabyte), Gi = Gibibyte (~GB)
      storage: 50Mi
